SOCIAL_AUTH_TWITTER_KEY = 'd7GqghPSipnSQIkmkDTk2XIkL'
SOCIAL_AUTH_TWITTER_SECRET = 'VFlmSAC0hd3M3EnXbkzzFvEzZjT1Lua9MPLwU1LE7xhHAa06Z8'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_URL = '/'