# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotDives', '0003_auto_20180223_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesitelist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
