# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scotDives', '0005_auto_20180224_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiveSiteList',
            new_name='DiveSite',
        ),
    ]
