# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotDives', '0006_auto_20180224_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='divesite',
            name='latitude',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='divesite',
            name='longitude',
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
