# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotDives', '0009_auto_20180312_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divesite',
            name='image',
            field=models.CharField(default='images/scotland.jpg', max_length=1000),
        ),
    ]
