# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotDives', '0011_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('pic', models.FileField(upload_to='')),
            ],
        ),
    ]
