# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scotDives', '0012_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='divesite',
            options={'verbose_name_plural': 'Divesites'},
        ),
        migrations.AddField(
            model_name='review',
            name='divesiteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scotDives.DiveSite'),
        ),
        migrations.AddField(
            model_name='review',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scotDives.UserProfile'),
        ),
    ]
