# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotDives', '0013_auto_20180317_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='divesiteid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='userid',
        ),
        migrations.AddField(
            model_name='review',
            name='divesite_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
