# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scotDives', '0014_auto_20180317_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='divesite_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='review',
            name='divesite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scotDives.DiveSite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
