# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotDives', '0015_auto_20180318_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
