# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scotDives', '0017_auto_20180318_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiveSpot',
        ),
    ]
